import type { CalculatedAnalysisModule } from "@/lib/analyses/types";
import { resolveDisplayValue } from "@/lib/analyses/ui";
import { getValueModule } from "@/lib/modules";

export function AssessmentForm({ module, action }: { module: CalculatedAnalysisModule; action: (formData: FormData) => Promise<void> }) {
  const definition = getValueModule(module.moduleKey);
  const persisted = new Map(module.inputs.map((input) => [input.inputKey, input.numericValue]));
  return <form action={action} className="space-y-5"><div className="grid gap-4 md:grid-cols-2">{[...definition.inputDefinitions].sort((a, b) => a.displayOrder - b.displayOrder).map((input) => { const resolved = resolveDisplayValue(input, persisted.get(input.key)); const issue = module.validationIssues.find((candidate) => candidate.field === input.key); return <label key={input.key} className="grid gap-2 text-sm font-semibold text-[#0b1d33]" htmlFor={input.key}>{input.label}<div className="flex rounded-lg border border-[#d7c9ae] bg-white focus-within:ring-2 focus-within:ring-[#d89b2b]">{input.type === "CURRENCY" && <span className="px-3 py-2 text-[#627085]">$</span>}<input id={input.key} name={input.key} type="number" step={input.type === "INTEGER" ? "1" : "any"} defaultValue={resolved.value ?? ""} className="min-w-0 flex-1 rounded-lg px-3 py-2 outline-none" aria-describedby={`${input.key}-help ${issue ? `${input.key}-error` : ""}`} />{input.type === "PERCENTAGE" && <span className="px-3 py-2 text-[#627085]">%</span>}</div><span id={`${input.key}-help`} className="text-xs font-normal leading-5 text-[#627085]">{input.helpText}{resolved.isDefault ? " Methodology default." : ""}</span>{issue && <span id={`${input.key}-error`} className="text-sm font-normal text-red-700">{issue.message}</span>}</label>; })}</div><button className="rounded-lg bg-[#d89b2b] px-5 py-3 font-semibold text-[#0b1d33]">Save & Calculate</button></form>;
}
