import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { WorkflowProgress } from "@/components/analysis/workflow-progress";
import { ReviewModuleCard } from "@/components/review/review-module-card";
import { calculateAnalysis } from "@/lib/analyses/service";
import { assessmentDisplayConfig, primaryFinancialLabels } from "@/lib/analyses/ui";
import { createNarrativeSourceFingerprint } from "@/lib/narratives/fingerprint";
import { renderAnalysisNarratives, resolveEffectiveNarrative, productContextForBusinessType } from "@/lib/narratives";
import { getCategoryByKey, getValueModule, valueTypes, type ValueType } from "@/lib/modules";
import { moveModuleAction, resetNarrativeAction, saveNarrativeAction } from "./actions";

type PageProps = { params: Promise<{ id: string }> };
const money = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 });
const valueTypeLabels: Record<ValueType, string> = { REVENUE_MARGIN_OPPORTUNITY: "Revenue & Margin Opportunity", COST_REDUCTION: "Operating Cost Reduction", CAPACITY_VALUE: "Labor Capacity Value", NET_CAPACITY_VALUE: "Net Capacity Value", COST_AVOIDANCE: "Cost Avoidance", CAPITAL_AVOIDANCE: "Capital Avoidance / Economic Equivalent" };
function fmt(raw: number, metric: { currency?: boolean; percent?: boolean; suffix?: string }) { if (metric.currency) return `${money.format(raw)}${metric.suffix ?? ""}`; if (metric.percent) return `${(raw * 100).toLocaleString()}%`; return `${raw.toLocaleString()}${metric.suffix ?? ""}`; }
function firstIncomplete(id: string, modules: readonly { moduleKey: string; status: string }[]) { const incomplete = modules.find(m => m.status !== "COMPLETE"); return `/analyses/${id}/assessment${incomplete ? `?module=${incomplete.moduleKey}` : ""}`; }

export default async function ReviewPage({ params }: PageProps) {
  const { id } = await params;
  const calculated = await calculateAnalysis({ analysisId: id });
  if (!calculated.ok) notFound();
  if (!calculated.value.workflowReadiness.canReview) redirect(firstIncomplete(id, calculated.value.calculatedModules));
  const narratives = renderAnalysisNarratives(calculated.value);
  if (!narratives.ok) notFound();
  const renderedById = new Map(calculated.value.calculatedModules.map((m, i) => [m.analysisModuleId, narratives.value[i]]));
  const byCategory = new Map<string, (typeof calculated.value.calculatedModules)[number][]>();
  for (const m of calculated.value.calculatedModules) {
    const group = byCategory.get(m.category) ?? [];
    group.push(m);
    byCategory.set(m.category, group);
  }
  const product = productContextForBusinessType(calculated.value.analysis.businessType) === "POWERBROKER" ? "PowerBroker" : "LoadMaster";
  const needsReviewCount = calculated.value.calculatedModules.filter(m => getValueModule(m.moduleKey).narrativeStatus === "NEEDS_PRODUCT_REVIEW").length;
  return <main className="min-h-screen bg-[#f8f1e4] px-8 py-10"><div className="mx-auto max-w-7xl space-y-8"><WorkflowProgress activeStage="review" analysisId={id} canReview={calculated.value.workflowReadiness.canReview} canGeneratePresentation={calculated.value.workflowReadiness.canGeneratePresentation} />
    <header className="rounded-3xl border border-[#e8dcc6] bg-[#fffaf0] p-10 shadow-sm"><p className="text-sm font-bold uppercase tracking-[0.18em] text-[#28614a]">{product} Value Analysis</p><h1 className="mt-2 text-4xl font-bold text-[#0b1d33]">Review Value Story</h1><p className="mt-3 max-w-3xl text-lg text-[#627085]">Review the financial opportunity, customer-specific analysis, and story order before generating the presentation.</p><div className="mt-6"><p className="text-3xl font-bold text-[#0b1d33]">{calculated.value.analysis.companyName}</p><p className="text-[#627085]">{calculated.value.analysis.businessType === "BROKERAGE" ? "Brokerage" : "Truckload"}</p></div></header>
    <section className="rounded-[2rem] bg-[#0b1d33] p-10 text-[#fffaf0]"><p className="text-sm font-bold uppercase tracking-[0.2em] text-[#d89b2b]">Annual Identified Economic Opportunity</p><p className="mt-3 text-6xl font-black">{money.format(calculated.value.summary.totalIdentifiedAnnualEconomicOpportunity)}</p><div className="mt-8 grid gap-4 md:grid-cols-3"><div><p className="text-3xl font-bold">{money.format(calculated.value.summary.monthlyRecurringValueTotal)} <span className="text-lg">/ MONTH</span></p><p className="text-sm uppercase tracking-[0.14em] text-[#d8e2ea]">Recurring Economic Opportunity</p></div><div><p className="text-3xl font-bold">{money.format(calculated.value.summary.annualRecurringValueTotal)}</p><p className="text-sm uppercase tracking-[0.14em] text-[#d8e2ea]">Annual Recurring Value</p></div>{calculated.value.summary.annualOnlyValueTotal > 0 && <div><p className="text-3xl font-bold">{money.format(calculated.value.summary.annualOnlyValueTotal)}</p><p className="text-sm uppercase tracking-[0.14em] text-[#d8e2ea]">Annual-Only Cost Avoidance</p></div>}</div></section>
    <section className="rounded-3xl border border-[#e8dcc6] bg-[#fffaf0] p-8"><h2 className="text-2xl font-bold text-[#0b1d33]">Value Type Breakdown</h2><div className="mt-5 grid gap-4 md:grid-cols-2">{valueTypes.map(v => calculated.value.summary.valueTypeBreakdown.find(b => b.valueType === v)).filter((b): b is NonNullable<typeof b> => !!b && b.annualEconomicOpportunity > 0).map(b => <div key={b.valueType} className="rounded-2xl bg-white/70 p-5"><h3 className="font-bold text-[#0b1d33]">{valueTypeLabels[b.valueType]}</h3>{b.monthlyRecurringValue > 0 && <p>{money.format(b.monthlyRecurringValue)} / month</p>}{b.annualRecurringValue > 0 && <p>{money.format(b.annualRecurringValue)} recurring annually</p>}{b.annualOnlyValue > 0 && <p>{money.format(b.annualOnlyValue)} annual-only</p>}<p className="font-bold">{money.format(b.annualEconomicOpportunity)} annual opportunity</p></div>)}</div></section>
    {calculated.value.summary.informationalCapitalValueTotal > 0 && <section className="rounded-3xl border border-[#d89b2b] bg-[#fff6df] p-8"><h2 className="text-2xl font-bold text-[#0b1d33]">Potential Avoided Capital Investment</h2><p className="mt-2 text-4xl font-bold text-[#0b1d33]">{money.format(calculated.value.summary.informationalCapitalValueTotal)}</p><p className="mt-3 text-[#35465c]">Informational capital values are shown separately from the annual economic opportunity because the recurring equivalent value is already represented in the analysis total.</p><ul className="mt-4 list-disc pl-5">{calculated.value.summary.informationalCapitalValues.map(i => <li key={i.analysisModuleId}>{getValueModule(i.moduleKey).name}: {money.format(i.value)}</li>)}</ul></section>}
    <section className="rounded-3xl border border-[#e8dcc6] bg-[#fffaf0] p-8"><h2 className="text-2xl font-bold text-[#0b1d33]">Assumption Review</h2>{calculated.value.overlapNotices.length === 0 ? <p className="mt-3 text-[#627085]">No potential value overlaps identified.</p> : <div className="mt-4 space-y-3">{calculated.value.overlapNotices.map(n => <div key={n.key} className="rounded-2xl border border-[#d7c9ae] bg-white p-4"><p className="font-bold">{n.type}</p><p>{n.message}</p></div>)}</div>}</section>
    {[...byCategory.entries()].map(([category, modules]) => <section key={category} className="space-y-5"><h2 className="text-2xl font-black uppercase tracking-[0.12em] text-[#0b1d33]">{getCategoryByKey(category as never)?.name}</h2>{modules.map((m, idx) => { const rendered = renderedById.get(m.analysisModuleId)!; const effective = resolveEffectiveNarrative({ renderedDefaultNarrative: rendered, narrativeMode: m.narrativeMode, customNarrative: m.customNarrative }); const currentFp = createNarrativeSourceFingerprint({ module: m, businessType: calculated.value.analysis.businessType }); const stale = m.narrativeMode === "CUSTOM" && m.customNarrativeSourceFingerprint !== currentFp; const outputs = m.calculationOutcome?.success ? m.calculationOutcome.result.financialOutputs : {}; const metric = outputs.monthlyRecurringValue ?? outputs.annualOnlyValue ?? 0; const cadence = outputs.monthlyRecurringValue !== undefined ? "/ MONTH" : "/ YEAR"; const cfg = assessmentDisplayConfig[m.moduleKey]; const derived = m.calculationOutcome?.success ? m.calculationOutcome.result.derivedMetrics : {}; return <ReviewModuleCard key={m.analysisModuleId} analysisModuleId={m.analysisModuleId} moduleName={getValueModule(m.moduleKey).name} valueTypeLabel={valueTypeLabels[m.valueType]} financialLabel={primaryFinancialLabels[m.moduleKey]} financialValue={money.format(metric)} financialCadence={cadence} assumptionItems={cfg.metrics.map(mm => { const raw = mm.source === "derived" ? derived[mm.key] : mm.source === "financial" ? outputs[mm.key as keyof typeof outputs] : m.reconstructedInputs[mm.key]; return { label: mm.label, value: raw === undefined ? "—" : fmt(Number(raw), mm) }; })} narrative={effective.ok ? effective.value : rendered.customerAnalysis} narrativeMode={m.narrativeMode} stale={stale} needsProductReview={getValueModule(m.moduleKey).narrativeStatus === "NEEDS_PRODUCT_REVIEW"} canMoveUp={idx > 0} canMoveDown={idx < modules.length - 1} saveAction={saveNarrativeAction.bind(null, id, m.analysisModuleId)} resetAction={resetNarrativeAction.bind(null, id, m.analysisModuleId)} moveUpAction={moveModuleAction.bind(null, id, m.analysisModuleId, "UP")} moveDownAction={moveModuleAction.bind(null, id, m.analysisModuleId, "DOWN")} />; })}</section>)}
    <section className="rounded-3xl border border-[#e8dcc6] bg-[#fffaf0] p-8"><h2 className="text-2xl font-bold text-[#0b1d33]">Presentation Readiness</h2><ul className="mt-4 space-y-2 text-[#35465c]"><li>✓ All calculations complete</li><li>✓ Narratives reviewed{needsReviewCount ? ` — ${needsReviewCount} Narratives Need Product Review` : ""}</li><li>✓ No blocking errors</li></ul><Link aria-disabled={!calculated.value.workflowReadiness.canGeneratePresentation} className="mt-6 inline-block rounded-lg bg-[#d89b2b] px-5 py-3 font-bold text-[#0b1d33]" href={`/analyses/${id}/presentation`}>Generate Presentation</Link></section>
  </div></main>;
}
