import { expect, test } from "@playwright/test";

test("West Side broker productivity workflow", async ({ page }) => {
  await page.goto("/");
  await page.getByRole("link", { name: "+ New Analysis" }).click();
  await page.getByLabel("Company Name").fill("West Side Transport");
  await page.getByLabel("Business Type").selectOption("BROKERAGE");
  await page.getByLabel("Prepared By").fill("Test User");
  await page.getByRole("button", { name: "Create Analysis" }).click();
  await expect(page.getByRole("heading", { name: "What opportunities were identified?" })).toBeVisible();
  await page.getByRole("button", { name: /Increase Broker Productivity/ }).click();
  await expect(page.getByText("1 Opportunity Selected")).toBeVisible();
  await page.getByRole("button", { name: "Continue to Assessment" }).click();
  await page.getByLabel("Current average loads per broker per day").fill("2");
  await page.getByLabel("Target average loads per broker per day").fill("3");
  await page.getByLabel("Number of brokers").fill("5");
  await page.getByLabel("Working days per month").fill("21");
  await page.getByRole("spinbutton", { name: "Average gross margin per brokered load" }).fill("50");
  await page.getByRole("button", { name: "Save & Calculate" }).click();
  await expect(page.getByText("Estimated Gross-Margin Opportunity")).toBeVisible();
  await expect(page.getByText("$5,250").first()).toBeVisible();
  await expect(page.getByText("/ MONTH")).toBeVisible();
  await expect(page.getByText(/105 additional monthly loads/)).toBeVisible();
  await expect(page.getByText(/West Side Transport/)).toBeVisible();
  await expect(page.getByText("COMPLETE")).toBeVisible();
  await expect(page.getByRole("link", { name: "Continue to Review" })).toBeVisible();
  const reviewHref = await page.getByRole("link", { name: "Continue to Review" }).getAttribute("href");
  await page.goto(reviewHref!);
  await expect(page.getByRole("heading", { name: "Review Value Story" })).toBeVisible();
  await expect(page.getByText("$63,000").first()).toBeVisible();
  await expect(page.getByText("Revenue & Margin Opportunity").first()).toBeVisible();
  await expect(page.getByRole("heading", { name: "Increase Broker Productivity" })).toBeVisible();
});

test("West Side review narrative edit stale reset handoff", async ({ page }) => {
  await page.goto("/");
  await page.getByRole("link", { name: "+ New Analysis" }).click();
  await page.getByLabel("Company Name").fill("West Side Transport");
  await page.getByLabel("Business Type").selectOption("BROKERAGE");
  await page.getByLabel("Prepared By").fill("Test User");
  await page.getByRole("button", { name: "Create Analysis" }).click();
  await expect(page.getByRole("heading", { name: "What opportunities were identified?" })).toBeVisible();
  await page.getByRole("button", { name: /Increase Broker Productivity/ }).click();
  await page.getByRole("button", { name: "Continue to Assessment" }).click();
  await page.getByLabel("Current average loads per broker per day").fill("0");
  await page.getByLabel("Target average loads per broker per day").fill("3.5");
  await page.getByLabel("Number of brokers").fill("5");
  await page.getByLabel("Working days per month").fill("20");
  await page.getByRole("spinbutton", { name: "Average gross margin per brokered load" }).fill("75");
  await page.getByRole("button", { name: "Save & Calculate" }).click();
  await expect(page.getByText("$26,250").first()).toBeVisible();
  await expect(page.getByText("COMPLETE")).toBeVisible();
  const reviewHref = await page.getByRole("link", { name: "Continue to Review" }).getAttribute("href");
  await page.goto(reviewHref!);
  await expect(page.getByRole("heading", { name: "Review Value Story" })).toBeVisible();
  await expect(page.getByText("$315,000").first()).toBeVisible();
  await expect(page.getByText("Revenue & Margin Opportunity").first()).toBeVisible();
  await expect(page.getByRole("heading", { name: "Increase Broker Productivity" })).toBeVisible();
  await expect(page.getByText(/West Side Transport currently averages/)).toBeVisible();

  await page.getByRole("button", { name: "Edit Analysis" }).click();
  const textarea = page.getByLabel("Customer analysis for Increase Broker Productivity");
  await textarea.fill(`${await textarea.inputValue()}\n\nWest Side's brokerage team will use the recovered capacity to pursue additional shipper volume.`);
  await page.getByRole("button", { name: "Save Analysis" }).click();
  await expect(page.getByText("Custom Narrative")).toBeVisible();
  await expect(page.getByText(/recovered capacity to pursue additional shipper volume/)).toBeVisible();

  await page.goto(reviewHref!.replace("/review", "/assessment?module=BROKER_PRODUCTIVITY"));
  await page.getByLabel("Target average loads per broker per day").fill("4");
  await page.getByRole("button", { name: "Save & Calculate" }).click();
  await expect(page.getByText("$30,000").first()).toBeVisible();
  await page.goto(reviewHref!);
  await expect(page.getByText("Custom Narrative May Need Review")).toBeVisible();
  await expect(page.getByText(/recovered capacity to pursue additional shipper volume/)).toBeVisible();
  await page.getByRole("button", { name: "Reset to Updated Default" }).click();
  await expect(page.getByText("Custom Narrative May Need Review")).not.toBeVisible();
  await expect(page.getByText(/4 loads per broker per day/)).toBeVisible();
  const presentationHref = await page.getByRole("link", { name: "Generate Presentation" }).getAttribute("href");
  await page.goto(presentationHref!);
  await expect(page.getByRole("heading", { name: "Generate Presentation" })).toBeVisible();
  await expect(page.getByText("Your reviewed value story is ready to be converted into an editable McLeod-branded PowerPoint presentation.")).toBeVisible();
});
