export const validationCodes = {
  REQUIRED_FINITE_NUMBER: "REQUIRED_FINITE_NUMBER",
  INTEGER_REQUIRED: "INTEGER_REQUIRED",
  NON_NEGATIVE_REQUIRED: "NON_NEGATIVE_REQUIRED",
  POSITIVE_REQUIRED: "POSITIVE_REQUIRED",
  PERCENTAGE_OUT_OF_RANGE: "PERCENTAGE_OUT_OF_RANGE",
  BELOW_MINIMUM: "BELOW_MINIMUM",
  ABOVE_MAXIMUM: "ABOVE_MAXIMUM",
  TARGET_MUST_BE_LOWER: "TARGET_MUST_BE_LOWER",
  TARGET_MUST_BE_HIGHER: "TARGET_MUST_BE_HIGHER",
  VALUE_EXCEEDS_CURRENT: "VALUE_EXCEEDS_CURRENT",
  INVALID_MODULE_INPUT: "INVALID_MODULE_INPUT",
} as const;

export type ValidationCode = (typeof validationCodes)[keyof typeof validationCodes];
